import type { BackendReport, ReportsStats } from "./api";

const ago = (hours: number) => new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();

export const MOCK_REPORTS_STATS: ReportsStats = {
  total_this_month: 24,
  ready_this_week: 6,
  scheduled: 2,
  pending: 0,
};

export const MOCK_REPORTS: BackendReport[] = [
  {
    id: "RPT-2407-018",
    template: "ops-daily",
    status: "READY",
    format: "PDF",
    date_range: "This Week · All vehicles",
    file_size: "842 KB",
    file_path: null,
    generated_at: ago(2),
    created_by: "Admin",
    created_at: ago(2),
  },
  {
    id: "RPT-2407-017",
    template: "revenue-breakdown",
    status: "READY",
    format: "CSV",
    date_range: "This Month · Cab Taxi",
    file_size: "1.2 MB",
    file_path: null,
    generated_at: ago(26),
    created_by: "Finance",
    created_at: ago(26),
  },
  {
    id: "RPT-2407-016",
    template: "driver-performance",
    status: "READY",
    format: "CSV",
    date_range: "This Month · Moto Bike",
    file_size: "156 KB",
    file_path: null,
    generated_at: ago(48),
    created_by: "Admin",
    created_at: ago(48),
  },
  {
    id: "RPT-2407-015",
    template: "ride-completion",
    status: "READY",
    format: "PDF",
    date_range: "Today · Gasabo",
    file_size: "620 KB",
    file_path: null,
    generated_at: ago(72),
    created_by: "Ops",
    created_at: ago(72),
  },
  {
    id: "RPT-2407-014",
    template: "negotiation-stats",
    status: "READY",
    format: "PDF",
    date_range: "This Week · All vehicles",
    file_size: "410 KB",
    file_path: null,
    generated_at: ago(96),
    created_by: "Admin",
    created_at: ago(96),
  },
  {
    id: "RPT-2407-013",
    template: "customer-overview",
    status: "READY",
    format: "PDF",
    date_range: "This Month",
    file_size: "890 KB",
    file_path: null,
    generated_at: ago(120),
    created_by: "Growth",
    created_at: ago(120),
  },
  {
    id: "RPT-2407-012",
    template: "ops-daily",
    status: "READY",
    format: "CSV",
    date_range: "Today · Light Hilux",
    file_size: "98 KB",
    file_path: null,
    generated_at: ago(140),
    created_by: "Admin",
    created_at: ago(140),
  },
  {
    id: "RPT-2407-011",
    template: "driver-performance",
    status: "READY",
    format: "PDF",
    date_range: "This Week · Kicukiro",
    file_size: "720 KB",
    file_path: null,
    generated_at: ago(168),
    created_by: "Ops",
    created_at: ago(168),
  },
];
